/* Vad passiven gör – spelets egen engelska text.
 *
 * GENERERAD ur samma uppströms-dataset som den statiska halvan
 * (`palworld-save-pal`, `data/json/l10n/en/passive_skills.json`). Skriv inte
 * här för hand: `npm run passive-text` säger vilka id:n som saknar text, och
 * filen görs om ur källan när den statiska halvan förnyas.
 *
 * Den svenska motsvarigheten i `passiveText.ts` är däremot handöversatt – där
 * står också varför tabellen behövs alls i stället för att härledas ur `fx`. */

export const PASSIVE_TEXT_EN: Record<string, string> = {
  Alien: "Attack +10.0% Fire damage reduction 15.0% Lightning damage reduction 15.0%",
  Attack_ACC_up4: "Attack +20.0%",
  Attack_ACC_up4_Armor: "Attack +12.0%",
  Attack_ACC_up4_Otomo_Only_Equip: "Attack +16.0%",
  AutoHPRegeneRate_Passive: "Player Auto Health Regeneration Rate +5.0%",
  CoolTimeReduction_Down_1: "Active skill cooldown extension -15.0%",
  CoolTimeReduction_Up_1: "Active skill cooldown reduction 30.0% Attack +10.0%",
  CoolTimeReduction_Up_2: "Active skill cooldown reduction 15.0%",
  CoolTimeReduction_Up_3: "Active skill cooldown reduction 0.0% Attack +0.0%",
  CraftSpeed_down1: "Work Speed -10.0%",
  CraftSpeed_down2: "Work Speed -30.0%",
  CraftSpeed_up1: "Work Speed +20.0%",
  CraftSpeed_up2: "Work Speed +50.0%",
  CraftSpeed_up3: "Work Speed +75.0%",
  Defense_ACC_up4_Otomo_Only_Equip: "Defense +20.0%",
  Deffence_down1: "Defense -10.0%",
  Deffence_down2: "Defense -20.0%",
  Deffence_up1: "Defense +10.0%",
  Deffence_up2: "Defense +20.0% Immune to Flinch",
  Deffence_up2_2: "Defense +20.0% Immune to Knockback",
  Deffence_up3: "Defense +30.0% Immune to Flinch Immune to Knockback",
  ElementBoost_Aqua_1_PAL: "10.0% increase in Water attack damage.",
  ElementBoost_Aqua_2_PAL: "30.0% increase in Water attack damage.",
  ElementBoost_Dark_1_PAL: "10.0% increase in Dark attack damage.",
  ElementBoost_Dark_2_PAL: "30.0% increase in Dark attack damage.",
  ElementBoost_Dark_4_Otomo_Only_Equip: "20.0% increase in Dark attack damage.",
  ElementBoost_Dragon_1_PAL: "10.0% increase in Dragon attack damage.",
  ElementBoost_Dragon_2_PAL: "30.0% increase in Dragon attack damage.",
  ElementBoost_Dragon_4_Otomo_Only_Equip: "20.0% increase in Dragon attack damage.",
  ElementBoost_Earth_1_PAL: "10.0% increase in Earth attack damage.",
  ElementBoost_Earth_2_PAL: "30.0% increase in Earth attack damage.",
  ElementBoost_Earth_4_Otomo_Only_Equip: "20.0% increase in Earth attack damage.",
  ElementBoost_Electricity_4_Otomo_Only_Equip: "20.0% increase in Lightning attack damage.",
  ElementBoost_Fire_1_PAL: "10.0% increase in Fire attack damage.",
  ElementBoost_Fire_2_PAL: "30.0% increase in Fire attack damage.",
  ElementBoost_Fire_4_Otomo_Only_Equip: "20.0% increase in Fire attack damage.",
  ElementBoost_Ice_1_PAL: "10.0% increase in Ice attack damage.",
  ElementBoost_Ice_2_PAL: "30.0% increase in Ice attack damage.",
  ElementBoost_Ice_4_Otomo_Only_Equip: "20.0% increase in Ice attack damage.",
  ElementBoost_Leaf_1_PAL: "10.0% increase in Grass attack damage.",
  ElementBoost_Leaf_2_PAL: "30.0% increase in Grass attack damage.",
  ElementBoost_Leaf_4_Otomo_Only_Equip: "20.0% increase in Grass attack damage.",
  ElementBoost_Normal_1_PAL: "10.0% increase in Neutral attack damage.",
  ElementBoost_Normal_2_PAL: "30.0% increase in Neutral attack damage.",
  ElementBoost_Normal_4_Otomo_Only_Equip: "20.0% increase in Neutral attack damage.",
  ElementBoost_Thunder_1_PAL: "10.0% increase in Lightning attack damage.",
  ElementBoost_Water_4_Otomo_Only_Equip: "20.0% increase in Water attack damage.",
  ElementResist_Aqua_1_PAL: "10.0% decrease in incoming Water damage.",
  ElementResist_Aqua_4: "35.0% decrease in incoming Water damage.",
  ElementResist_Dark_1_PAL: "10.0% decrease in incoming Dark damage.",
  ElementResist_Dark_4: "35.0% decrease in incoming Dark damage.",
  ElementResist_Dragon_1_PAL: "10.0% decrease in incoming Dragon damage.",
  ElementResist_Dragon_4: "35.0% decrease in incoming Dragon damage.",
  ElementResist_Earth_1_PAL: "10.0% decrease in incoming Earth damage.",
  ElementResist_Earth_4: "35.0% decrease in incoming Earth damage.",
  ElementResist_Fire_1_PAL: "10.0% decrease in incoming Fire damage.",
  ElementResist_Fire_4: "35.0% decrease in incoming Fire damage.",
  ElementResist_Ice_1_PAL: "10.0% decrease in incoming Ice damage.",
  ElementResist_Ice_4: "35.0% decrease in incoming Ice damage.",
  ElementResist_Leaf_1_PAL: "10.0% decrease in incoming Grass damage.",
  ElementResist_Leaf_4: "35.0% decrease in incoming Grass damage.",
  ElementResist_Normal_1_PAL: "10.0% decrease in incoming Neutral damage.",
  ElementResist_Normal_4: "35.0% decrease in incoming Neutral damage.",
  ElementResist_Thunder_1_PAL: "10.0% decrease in incoming Lightning damage.",
  ElementResist_Thunder_4: "35.0% decrease in incoming Lightning damage.",
  EternalFlame: "30.0% increase to Fire attack damage. 30.0% increase to Lightning attack damage.",
  FriendshipPoint_Increase_EquipSkill: "Trust +50.0%",
  HP_ACC_up4: "Max Health +25.0%",
  Invader: "30.0% increase in Dark attack damage. 30.0% increase in Dragon attack damage.",
  Legend: "Attack +20.0% Defense +20.0% Movement Speed increases 20.0%",
  MaxInventoryWeight_up_Equip_1: "Carrying Capacity +50.0%",
  MaxInventoryWeight_up_Equip_2: "Carrying Capacity +100.0%",
  MaxInventoryWeight_up_Equip_3: "Carrying Capacity +200.0%",
  MaxInventoryWeight_up_Equip_4: "Carrying Capacity +300.0%",
  MiniNushi: "5.0% increase to Water attack damage 5.0% increase to Ice attack damage 5.0% increase to defense.",
  MoveSpeed_up_1: "10.0% increase to movement speed.",
  MoveSpeed_up_2: "20.0% increase to movement speed.",
  MoveSpeed_up_3: "30.0% increase to movement speed.",
  MutationPal_Babysitter: "While at a base, increases egg production speed by +30.0% and incubation speed by +30.0% for Pals assigned to a Breeding Farm.",
  MutationPal_ExplosionResist: "<Status_Up>Immune</> to Explosion Damage",
  MutationPal_Immortal: "Life Steal +5.0% Pal Auto Health Regeneration Rate +100.0% Attack +15.0%",
  MutationPal_Mutant: "Pal and Player Auto Health Regeneration Rate +50.0% Defense +25.0% <Status_Up>Immune</> to Poison Damage <Status_Up>Immune</> to Burn Damage",
  NightOwl: "Tends to nap through the day, due to being nocturnal.",
  Nocturnal: "Does not sleep and continues to work even at night.",
  NonKilling: "Pacifist. Will not reduce the target's Health below 1.",
  Noukin: "Attack +30.0% Work Speed -50.0%",
  Nushi: "20.0% increase to Water attack damage 20.0% increase to Ice attack damage 20.0% increase to defense.",
  OctaviaArmorVampire: "Absorbs a portion of the damage dealt to restore Health. Does not sleep at night and continues to work.",
  PAL_ALLAttack_down1: "Attack -10.0%",
  PAL_ALLAttack_down2: "Attack -20.0%",
  PAL_ALLAttack_up1: "Attack +10.0%",
  PAL_ALLAttack_up2: "Attack +20.0%",
  PAL_ALLAttack_up3: "Attack +30.0% Defense +5.0%",
  PAL_CorporateSlave: "Work Speed +30.0% Attack -30.0%",
  PAL_FullStomach_Down_1: "Hunger decreases <NumBlue_13>+10.0%</> slower.",
  PAL_FullStomach_Down_2: "Hunger decreases <NumBlue_13>+15.0%</> slower.",
  PAL_FullStomach_Down_3: "Hunger decreases <NumBlue_13>+20.0%</> slower.",
  PAL_FullStomach_Up_1: "Hunger decreases <NumRed_13>+10.0%</> faster.",
  PAL_FullStomach_Up_2: "Hunger decreases <NumRed_13>+15.0%</> faster.",
  PAL_Sanity_Down_1: "SAN drops <NumBlue_13>+10.0%</> slower.",
  PAL_Sanity_Down_2: "SAN drops <NumBlue_13>+15.0%</> slower.",
  PAL_Sanity_Down_3: "SAN drops <NumBlue_13>+20.0%</> slower.",
  PAL_Sanity_Up_1: "SAN drops <NumRed_13>+10.0%</> faster.",
  PAL_Sanity_Up_2: "SAN drops <NumRed_13>+15.0%</> faster.",
  PAL_SpiritualInst: "Work Speed -10.0% Defense -10.0%",
  PAL_conceited: "Work Speed +10.0% Defense -10.0%",
  PAL_masochist: "Defense +15.0% Attack -15.0%",
  PAL_oraora: "Attack +10.0% Defense -10.0%",
  PAL_rude: "Attack +15.0% Work Speed -10.0%",
  PAL_sadist: "Attack +15.0% Defense -15.0%",
  PlayerSP_DecreaseRate_Passive: "Player Stamina Consumption -<NumBlue_13>5.0</>%",
  Rare: "Attack +15.0% Defense +15.0% Work Speed +20.0%",
  ReloadSpeedUp_Passive: "Player Reload Speed +4.0%",
  RideJumpCount_Increase1: "Mounted Jump Count +1",
  RideJumpCount_Increase2: "Mounted Jump Count +2",
  SalePrice_Down_1: "Decrease the value of items when sold by -10.0%",
  SalePrice_Up_1: "Increases the value of items when sold by +5.0%",
  SalePrice_Up_2: "Increases the value of items when sold by +3.0%",
  Salvation: "30.0% increase in Neutral attack damage. 30.0% increase in Grass attack damage.",
  SelfDeathAddItemDrop_up_2: "Your Dropped Items + 50.0%",
  SelfDeathAddItemDrop_up_3: "Your Dropped Items + 100.0%",
  Stamina_Down_1: "Max Stamina -25.0% *This effect is only valid for rideable pals.",
  Stamina_Up_1: "Max stamina +50.0% *This effect is only valid for rideable pals.",
  Stamina_Up_2: "Max stamina +25.0% *This effect is only valid for rideable pals.",
  Stamina_Up_3: "Max stamina +75.0% *This effect is only valid for rideable pals.",
  StonDrop_Boost_5: "Massively increases the drop amount of Stone and Ore.",
  SwimSpeed_up_1: "30.0% increase movement speed on water.",
  SwimSpeed_up_2: "40.0% increase movement speed on water.",
  SwimSpeed_up_3: "50.0% increase movement speed on water.",
  Test_PalEgg_HatchingSpeed_Up: "When assigned to a Breeding Farm, breeding speed is increased by 100.0%.",
  TrainerATK_UP_1: "10.0% increase in Player Attack.",
  TrainerDEF_UP_1: "10.0% increase in Player Defense.",
  TrainerLogging_up1: "25.0% increase in Player Logging Efficiency.",
  TrainerMining_up1: "25.0% increase in Player Mining Efficiency.",
  TrainerWorkSpeed_UP_1: "25.0% increase in Player Work Speed.",
  Vampire: "Absorbs a portion of the damage dealt to restore Health. Does not sleep at night and continues to work.",
  Witch: "30.0% increase in Dark attack damage. 30.0% increase in Ice attack damage.",
  WoodDrop_Boost_5: "Massively increases the drop amount of Wood.",
  WorkSpeed_ACC_up4: "Work Speed +25.0%",
  WorkSuitabilityAddRank_MonsterFarm_1: "Farming's Work Suitability<NumBlue_13> +1</>",
  WorkSuitabilityAddRank_MonsterFarm_2: "Farming's Work Suitability<NumBlue_13> +2</>",
  WorldTree_ATK: "Attack <NumBlue_13>+</>50.0% Defense -30.0% World Tree resources will not vanish when approached.",
  WorldTree_ATK_DEF: "Attack <NumBlue_13>+</>40.0% Defense <NumBlue_13>+</>20.0% Max Health -50.0% World Tree resources will not vanish when approached.",
  WorldTree_CraftSpeed: "Work Speed <NumBlue_13>+</>90.0<NumBlue_13>%</> SAN dreceases <NumRed_13>+15.0% faster</> World Tree harvestables won't vanish when approached.",
  WorldTree_DEF: "Defense <NumBlue_13>+</>50.0% Attack -30.0% World Tree resources will not vanish when approached.",
  WorldTree_FullStomach: "Decrease Hunger depletion rate by <NumBlue_13>+50.0%</> HP -20.0<NumRed_13>%</> World Tree resources will not vanish when approached.",
  WorldTree_MoveSpeed: "Movement Speed <NumBlue_13>+</>50.0<NumBlue_13>%</> Increases Hunger depletion rate by <NumRed_13>+15.0%</> World Tree resources will not vanish when approached.",
  WorldTree_Sanity: "SAN depletion rate -<NumBlue_13>50.0%</> Work Speed -20.0<NumRed_13>%</> World Tree resources will not vanish when approached.",
  YakushimaDagameBoost_Magic_Equip: "DamageUpIfEquipped_YakushimaMagicWeapon +20.0%",
  YakushimaDagameBoost_Melee_Equip: "DamageUpIfEquipped_YakushimaMeleeWeapon +20.0%",
  YakushimaDagameBoost_Ranged_Equip: "DamageUpIfEquipped_YakushimaRangedWeapon +20.0%",
  YakushimaDagameBoost_Summon_Equip: "DamageUpIfEquipped_YakushimaSummonWeapon +20.0%",
  YakushimaProtection_Equip: "ForYakushimaDefenceRate +30.0%",
  defense_ACC_up4: "Defense +25.0%",
};
